### ISSUE TITLE
Publish package to npm

### ISSUE THREAD

**Issue by manask88** [Jpoliachik/react-native-triangle#1]
Thanks for your contribution to the open source community. This is a great project. I would like to use it in one of my projects but I’m only allowed to use it if it’s publish on npm. Can you please create an npm release for this?  If you need help, let me know

**Comment by Jpoliachik** [comment]
Done!

`npm react-native-triangle`

https://www.npmjs.com/package/react-native-triangle

**Comment by Jpoliachik** [comment]
@manask88 I'm able to install the module in a project, but `require('react-native-triangle')` doesn't seem to recognize it. Did I miss something?

**Comment by manask88** [comment]
There is a very small typo in your package.json file.
It says

```javascript
 "main": "triangle.js"
```

It should say:

```javascript
 "main": "Triangle.js"
```

**Comment by Jpoliachik** [comment]
Good catch! Thanks. Should be good to go now.
