### ISSUE TITLE
Not working properly with react native 0.57.4

### ISSUE THREAD

**Issue by mezod** [Jpoliachik/react-native-triangle#10]
Hey, since I upgraded to 0.57.4 triangles dont seem to get rendered properly anymore on iOS.

From this issue: https://github.com/facebook/react-native/issues/21945 I get that the problem is from native's new version but I wonder if anyone has found a temporal solution? It doesn't look like a bug they'll prioritize... rendering this lib useless :(

Thanks!

**Comment by FadiAboMsalam** [comment]
any one found a temp solution for this ?

**Comment by mezod** [comment]
I undid this commit on my node_modules instance of react-native https://github.com/facebook/react-native/commit/dba2235d95e46514206bcfaefc7e965193536fe8

shitty workaround ;(

**Comment by johman10** [comment]
Just an FYI for anyone running into this: you can add a borderRadius to the triangle to fix this.

I added comment on the issue: https://github.com/facebook/react-native/issues/21945#issuecomment-473965109

**Comment by mezod** [comment]
nice find, thanks for sharing! :)
