### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by ashleydw** [Jpoliachik/react-native-triangle#3]
Rendering in android fails for me. Using "left" I get nothing, using "up" I get the following (red is the triangle, blue it's container)

![image](https://cloud.githubusercontent.com/assets/844437/12239379/c2256ad0-b888-11e5-8099-e4a4683f9a0e.png)

Is this known, or is there no support for android at this time?

**Comment by Jpoliachik** [comment]
@ashleydw I haven't tested on Android yet, sorry! What version of react-native are you using? I'll take a look at this tonight.

**Comment by Nyte7** [comment]
Seems like this is a general issue with react native and android as even the manual CSS method does not work (only produces rectangles).

**Comment by Jpoliachik** [comment]
I'm able to reproduce the issue. Unfortunately, I don't know if theres anything I can do at the moment. It seems the borderWidth and borderColor tricks that work in iOS to produce triangles do not work with Android's layout engine in react-native.

I submitted an issue in the react-native repo. https://github.com/facebook/react-native/issues/5411

Until this is resolved, using assets might be the only solution for Android. 

Using RNPlay and react-native v 0.13.0-rc, Android looks like this: 
![screen shot 2016-01-19 at 10 02 37 am](https://cloud.githubusercontent.com/assets/5148640/12422221/d928ceb4-be93-11e5-9a8e-879fa7410624.png)

iOS Looks like this: 
![screen shot 2016-01-19 at 10 02 23 am](https://cloud.githubusercontent.com/assets/5148640/12422223/db4812a4-be93-11e5-82c0-bc67bb18d688.png)

**Comment by ashleydw** [comment]
FYI, these are working on RN 0.22

via https://github.com/facebook/react-native/pull/5911
