### ISSUE TITLE
Is it possible to create a "hollow" triangle?

### ISSUE THREAD

**Issue by salmankhann** [Jpoliachik/react-native-triangle#5]
Is it possible to create a triangle with no fill but only borders?

**Comment by Jpoliachik** [comment]
Unfortunately, not with this method. You'll need to use React Native ART or some other SVG renderer like [react-native-svg](https://github.com/react-native-community/react-native-svg)

**Comment by FanchenBao** [comment]
This answer is four years too late, but you can create a "hollow" triangle (white background with black edges) by placing a slightly smaller white triangle on top of a black triangle. This creates an illusion of a "hollow" triangle.
